apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: app2
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: {{.Values.container.image}}
        args:
          - {{.Values.container.arg2}}
        ports:
        - containerPort: {{.Values.container.port}}
