apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service2.name}}
spec:
  type: {{.Values.service2.type}}
  selector:
    app: app2
  ports:
  - protocol: TCP
    port: {{.Values.container.port}}
    targetPort: {{.Values.container.port}}
