apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service1.name}}
spec:
  type: {{.Values.service1.type}}
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: {{.Values.container.port}}
    targetPort: {{.Values.container.port}}
