apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app3
  labels:
    appthree: app3
    app: test
spec:
  selector:
    matchLabels:
      appthree: app3
      app: test
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        appthree: app3
        app: test
    spec:
      containers:
      - image: kalyanich/app3
        name: app3
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
